#!/bin/sh
# install_termux.sh — install the `hermes-os` wrapper into ~/.local/bin.
#
# What this does:
#   1. sanity-checks the environment (POSIX shell + python3),
#   2. creates ~/.local/bin if needed,
#   3. writes a small wrapper with THIS repo's absolute path baked in,
#   4. tells you how to run it.
#
# What this NEVER does:
#   - modify Hermes cron jobs, profiles, memory, or gateway state,
#   - overwrite an existing ~/.local/bin/hermes-os that it didn't create
#     (unless you re-run with FORCE=1),
#   - touch anything outside ~/.local/bin and the product's own state dir.
set -eu

MARKER="# hermes-android-agentic-os wrapper v1"
REPO_DIR=$(cd "$(dirname "$0")/.." && pwd)
BIN_DIR="${HOME}/.local/bin"
TARGET="${BIN_DIR}/hermes-os"

echo "hermes-android-agentic-os installer"
echo "repo: ${REPO_DIR}"

# --- environment checks ------------------------------------------------
if [ -n "${TERMUX_VERSION:-}" ] || [ -d /data/data/com.termux/files/usr ]; then
  echo "env:  Termux detected"
else
  echo "env:  not Termux — proceeding anyway (Linux-like shell assumed)"
fi

PY=python3
command -v python3 >/dev/null 2>&1 || PY=python
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "error: python3 not found. In Termux run: pkg install python" >&2
  exit 1
fi

SH_BIN=$(command -v sh || true)
if [ -z "$SH_BIN" ]; then
  echo "error: POSIX sh not found" >&2
  exit 1
fi

if [ ! -f "${REPO_DIR}/hermes_os/cli.py" ]; then
  echo "error: ${REPO_DIR} does not look like the product repo" >&2
  exit 1
fi

# --- refuse to clobber unrelated files ---------------------------------
if [ -e "$TARGET" ] && ! grep -q "$MARKER" "$TARGET" 2>/dev/null; then
  if [ "${FORCE:-0}" != "1" ]; then
    echo "error: $TARGET exists and was not created by this installer." >&2
    echo "       Inspect it, then re-run with FORCE=1 to overwrite." >&2
    exit 1
  fi
  echo "warn: overwriting foreign $TARGET because FORCE=1"
fi

# --- install ------------------------------------------------------------
mkdir -p "$BIN_DIR"
TMP="${TARGET}.tmp.$$"
cat > "$TMP" <<EOF
#!${SH_BIN}
${MARKER}
# Generated by install_termux.sh — points at the repo below.
set -eu
REPO_DIR="${REPO_DIR}"
PY=python3
command -v python3 >/dev/null 2>&1 || PY=python
PYTHONPATH="\${REPO_DIR}\${PYTHONPATH:+:\$PYTHONPATH}" exec "\$PY" -m hermes_os.cli "\$@"
EOF
chmod +x "$TMP"
mv "$TMP" "$TARGET"
echo "ok:   installed $TARGET"

# --- PATH hint ----------------------------------------------------------
case ":${PATH}:" in
  *":${BIN_DIR}:"*) : ;;
  *)
    echo
    echo "note: ${BIN_DIR} is not on your PATH. Add this to ~/.bashrc or ~/.zshrc:"
    echo "      export PATH=\"\$HOME/.local/bin:\$PATH\""
    ;;
esac

echo
echo "Try it:"
echo "  hermes-os doctor"
echo "  hermes-os status"
echo "  hermes-os render-html   # then: termux-open ${REPO_DIR}/dist/index.html"
echo
echo "Nothing in your Hermes cron/gateway/profile config was modified."
